Repository DearBelly/DearBelly-BE-Spring, pull requests merged in 2025-09, with the labels that each got.

#116 [REFACTOR] HMAC 서명 기반 가족 코드와 활성화 코드 재사용
  src/main/java/com/hanium/mom4u/domain/family/service/FamilyService.java
  src/main/java/com/hanium/mom4u/global/security/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨Feature, ♻️Refactor, 효린

#120 [REFACTOR] S3 Presigned URL Blob 업로드 호환성 개선
  src/main/java/com/hanium/mom4u/domain/member/controller/MemberController.java
  src/main/java/com/hanium/mom4u/domain/member/dto/request/ImageCommitRequest.java
  src/main/java/com/hanium/mom4u/domain/member/dto/request/ProfileEditRequest.java
  src/main/java/com/hanium/mom4u/domain/member/dto/response/UploadUrlResponse.java
  src/main/java/com/hanium/mom4u/domain/member/service/MemberService.java
  src/main/java/com/hanium/mom4u/domain/news/dto/response/NewsDetailResponseDto.java
  src/main/java/com/hanium/mom4u/domain/news/dto/response/NewsPreviewResponseDto.java
  src/main/java/com/hanium/mom4u/external/s3/service/FileStorageService.java
  src/main/java/com/hanium/mom4u/global/response/StatusCode.java
Labels: 🐛Bug, ♻️Refactor, 효린

#121 [FEATURE] 모니터링 확장하기
  deploy/docker/docker-compose.blue.yml
  deploy/docker/docker-compose.monitor.yml
  deploy/monitoring/loki-config.yml
  deploy/monitoring/prometheus.yml
  deploy/monitoring/promtail-config.yml
  deploy/nginx/nginx.blue.conf
  deploy/nginx/nginx.green.conf
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
Labels: ✨Feature, 유연

#128 [REFACTOR] News Entity 고유성 보장 및 Lambda 구조 개선
  .github/workflows/gradle.yml
  src/main/java/com/hanium/mom4u/domain/news/entity/News.java
  src/main/java/com/hanium/mom4u/domain/news/listener/NewsScheduler.java
  src/main/java/com/hanium/mom4u/domain/news/listener/S3JsonImportEventHandler.java
  src/main/java/com/hanium/mom4u/domain/news/repository/NewsJdbcRepository.java
  src/main/java/com/hanium/mom4u/domain/news/repository/NewsRepositoryCustom.java
  src/main/java/com/hanium/mom4u/domain/news/repository/NewsRepositoryCustomImpl.java
  src/main/java/com/hanium/mom4u/global/crawling/controller/CrawlTestController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ♻️Refactor, 유연

#129 DEPLOY - v1.1.6
  .github/workflows/gradle.yml
  src/main/java/com/hanium/mom4u/domain/news/entity/News.java
  src/main/java/com/hanium/mom4u/domain/news/listener/NewsScheduler.java
  src/main/java/com/hanium/mom4u/domain/news/listener/S3JsonImportEventHandler.java
  src/main/java/com/hanium/mom4u/domain/news/repository/NewsJdbcRepository.java
  src/main/java/com/hanium/mom4u/domain/news/repository/NewsRepositoryCustom.java
  src/main/java/com/hanium/mom4u/domain/news/repository/NewsRepositoryCustomImpl.java
  src/main/java/com/hanium/mom4u/global/crawling/controller/CrawlTestController.java
  src/main/java/com/hanium/mom4u/global/security/config/SecurityConfig.java
  src/main/java/com/hanium/mom4u/global/security/jwt/JwtAuthenticationFilter.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🌏Deploy

#134 [HOTFIX] 리다이렉트 URI 오타 수정 및 오류 개선
  src/main/java/com/hanium/mom4u/domain/family/entity/DailyQuestion.java
  src/main/java/com/hanium/mom4u/domain/family/entity/Family.java
  src/main/java/com/hanium/mom4u/domain/member/entity/Member.java
  src/main/java/com/hanium/mom4u/domain/member/repository/MemberRepository.java
  src/main/java/com/hanium/mom4u/domain/question/service/.gitkeep
  src/main/java/com/hanium/mom4u/domain/question/service/LetterService.java
  src/main/java/com/hanium/mom4u/domain/sse/controller/SseController.java
  src/main/java/com/hanium/mom4u/domain/sse/dto/MessageDto.java
  src/main/java/com/hanium/mom4u/domain/sse/repository/SseRepository.java
  src/main/java/com/hanium/mom4u/domain/sse/service/SseService.java
  src/main/java/com/hanium/mom4u/external/redis/config/RedisConfig.java
  src/main/java/com/hanium/mom4u/external/redis/config/RedisPubSubConfig.java
  src/main/java/com/hanium/mom4u/external/redis/publisher/MessagePublisher.java
  src/main/java/com/hanium/mom4u/external/redis/subscribe/MessageSubscriber.java
  src/main/java/com/hanium/mom4u/global/config/MvcAsyncConfig.java
  src/main/java/com/hanium/mom4u/global/filter/LoggingFilter.java
  src/main/java/com/hanium/mom4u/global/response/StatusCode.java
Labels: 🐛Bug

#137 [FEATURE] 질문 관련 알림 전송 및 읽음 여부 조회 기능 구현
  deploy/local/Dockerfile
  deploy/local/docker-compose.local.yaml
  deploy/local/prometheus-local.yml
  src/main/java/com/hanium/mom4u/domain/member/entity/Member.java
  src/main/java/com/hanium/mom4u/domain/news/repository/NewsJdbcRepository.java
  src/main/java/com/hanium/mom4u/domain/question/controller/LetterController.java
  src/main/java/com/hanium/mom4u/domain/question/dto/response/LetterCheckResponseDto.java
  src/main/java/com/hanium/mom4u/domain/question/dto/response/LetterResponse.java
  src/main/java/com/hanium/mom4u/domain/question/entity/Letter.java
  src/main/java/com/hanium/mom4u/domain/question/entity/LetterRead.java
  src/main/java/com/hanium/mom4u/domain/question/repository/LetterRepository.java
  src/main/java/com/hanium/mom4u/domain/question/repository/LetterRepositoryCustom.java
  src/main/java/com/hanium/mom4u/domain/question/repository/LetterRepositoryCustomImpl.java
  src/main/java/com/hanium/mom4u/domain/question/service/LetterService.java
  src/main/java/com/hanium/mom4u/global/config/SwaggerConfig.java
  src/main/java/com/hanium/mom4u/global/config/WebMVCConfig.java
  src/main/resources/application-local.yml
  src/test/java/com/hanium/mom4u/domain/questions/service/LetterReadTest.java
Labels: ✨Feature, 유연

#140 [REFACTOR] Question 로직 분리와 QueryDSL 로 query 개선
  src/main/java/com/hanium/mom4u/domain/family/entity/DailyQuestion.java
  src/main/java/com/hanium/mom4u/domain/family/entity/Question.java
  src/main/java/com/hanium/mom4u/domain/question/dto/response/TodayWriteResponse.java
  src/main/java/com/hanium/mom4u/domain/question/repository/DailyQuestionRepository.java
  src/main/java/com/hanium/mom4u/domain/question/repository/DailyQuestionRepositoryCustom.java
  src/main/java/com/hanium/mom4u/domain/question/repository/DailyQuestionRepositoryImpl.java
  src/main/java/com/hanium/mom4u/domain/question/service/LetterService.java
  src/main/java/com/hanium/mom4u/domain/question/service/QuestionService.java
  src/main/java/com/hanium/mom4u/global/response/StatusCode.java
  src/test/java/com/hanium/mom4u/domain/questions/repository/DailyQuestionRepositoryImplTest.java
  src/test/java/com/hanium/mom4u/domain/questions/repository/LetterRepositoryTest.java
  src/test/java/com/hanium/mom4u/domain/questions/service/LetterReadTest.java
  src/test/java/com/hanium/mom4u/domain/questions/service/QuestionServiceTest.java
Labels: ♻️Refactor, 효린
