Repository DearBelly/DearBelly-BE-Spring, pull requests merged in 2025-10, with the labels that each got.

#144 [FIX] MVC 필터 상의 문제 해결
  deploy/nginx/nginx.blue.conf
  deploy/nginx/nginx.green.conf
  src/main/java/com/hanium/mom4u/domain/question/controller/QuestionController.java
  src/main/resources/application-dev.yml
Labels: 🐛Bug, 🛠Fix, 유연

#148 [FEATURE] 로그인 시 신규회원여부 반환
  src/main/java/com/hanium/mom4u/domain/member/entity/Member.java
  src/main/java/com/hanium/mom4u/domain/member/repository/MemberRepository.java
  src/main/java/com/hanium/mom4u/global/security/dto/response/GoogleProfileResponseDto.java
  src/main/java/com/hanium/mom4u/global/security/dto/response/LoginResponseDto.java
  src/main/java/com/hanium/mom4u/global/security/dto/response/NaverProfileResponseDto.java
  src/main/java/com/hanium/mom4u/global/security/service/GoogleLoginService.java
  src/main/java/com/hanium/mom4u/global/security/service/KakaoLoginService.java
  src/main/java/com/hanium/mom4u/global/security/service/NaverLoginService.java
Labels: ✨Feature, 효린

#156 DEPLOY - v1.1.7.4
  deploy/docker/deploy.sh
  deploy/docker/docker-compose.blue.yml
  deploy/docker/docker-compose.green.yml
  src/main/java/com/hanium/mom4u/domain/family/entity/Family.java
  src/main/java/com/hanium/mom4u/domain/family/service/FamilyService.java
Labels: 🌏Deploy
